# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['number']},
        ),
    ]
