# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Starship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('length', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Droid',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='starwars.Character')),
                ('primary_function', models.CharField(max_length=255)),
            ],
            bases=('starwars.character',),
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('character_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='starwars.Character')),
                ('total_credits', models.PositiveSmallIntegerField(default=0)),
                ('starships', models.ManyToManyField(to='starwars.Starship')),
            ],
            bases=('starwars.character',),
        ),
        migrations.AddField(
            model_name='character',
            name='appears_in',
            field=models.ManyToManyField(to='starwars.Episode'),
        ),
        migrations.AddField(
            model_name='character',
            name='friends',
            field=models.ManyToManyField(related_name='_character_friends_+', to='starwars.Character'),
        ),
    ]
