# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='appears_in',
            field=models.ManyToManyField(blank=True, to='starwars.Episode'),
        ),
        migrations.AlterField(
            model_name='character',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_character_friends_+', to='starwars.Character'),
        ),
    ]
