# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starwars', '0002_auto_20170901_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='appears_in',
            field=models.ManyToManyField(blank=True, related_name='characters', to='starwars.Episode'),
        ),
    ]
